// File generated by Antigravity based on google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuGJbAZkj2GKNc4fTPy6DvKu4aVgK_zw',
    appId: '1:297849799066:android:1709c7e43a8c1b2e06ba23',
    messagingSenderId: '297849799066',
    projectId: 'tokri-6146f',
    storageBucket: 'tokri-6146f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuGJbAZkj2GKNc4fTPy6DvKu4aVgK_zw',
    appId: '1:297849799066:android:1709c7e43a8c1b2e06ba23',
    messagingSenderId: '297849799066',
    projectId: 'tokri-6146f',
    storageBucket: 'tokri-6146f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJuGJbAZkj2GKNc4fTPy6DvKu4aVgK_zw',
    appId: '1:297849799066:android:1709c7e43a8c1b2e06ba23',
    messagingSenderId: '297849799066',
    projectId: 'tokri-6146f',
    storageBucket: 'tokri-6146f.firebasestorage.app',
    iosBundleId: 'com.tokri.tokri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJuGJbAZkj2GKNc4fTPy6DvKu4aVgK_zw',
    appId: '1:297849799066:android:1709c7e43a8c1b2e06ba23',
    messagingSenderId: '297849799066',
    projectId: 'tokri-6146f',
    storageBucket: 'tokri-6146f.firebasestorage.app',
    iosBundleId: 'com.tokri.tokri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJuGJbAZkj2GKNc4fTPy6DvKu4aVgK_zw',
    appId: '1:297849799066:android:1709c7e43a8c1b2e06ba23',
    messagingSenderId: '297849799066',
    projectId: 'tokri-6146f',
    storageBucket: 'tokri-6146f.firebasestorage.app',
  );
}
